runtime: php55
api_version: 1

default_expiration: "1h"

handlers:
- url: /css
  static_dir: app/css

- url: /images
  static_dir: app/images

- url: /js
  static_dir: app/js
  http_headers:
    Service-Worker-Allowed: /

- url: /static
  static_dir: app/static

- url: /robots.txt
  static_files: app/static/robots.txt
  upload: app/static/robots.txt
  secure: always

- url: /humans.txt
  static_files: static/humans.txt
  upload: app/static/humans.txt
  secure: always

- url: /sitemap.xml
  static_files: app/static/sitemap.xml
  upload: app/static/sitemap.xml
  secure: always

- url: /manifest.json
  static_files: app/static/manifest.json
  upload: app/static/manifest.json
  secure: always

- url: /.*
  script: index.php
  secure: always